import * as THREE from './vendor/three.module.js';
import {PROJECTS} from './projects.js';
import {createScreenCanvas,hitButton} from './screen-canvas.js';

export const PROJECT_SUMMARIES={
  synari:'An AI-powered workspace that helps therapists manage notes, scheduling, and the busywork of running a practice.',
  autoapply:'A local job-search assistant that finds SWE roles, drafts tailored applications, and helps fill them in.',
  autotrader:'An automated swing-trading engine that pairs market signals with AI review and strict risk limits.',
  signlang:'An accessible interface that translates one-handed inputs into digital sign-language gestures.',
  audit:'A Chrome extension that checks whether artwork you find online was generated by AI.',
  rant:'An AI-powered journal that helps you express your thoughts and reflect on how you feel.',
  tutorwiz:'A tutoring platform with personalized sessions, adaptive learning paths, and AI study support.',
  asktestudo:'An AI assistant that helps UMD students navigate courses, schedules, prerequisites, and registration.',
};
export const DESKTOP_ICONS=Object.keys(PROJECTS).map((id,i)=>({id,x:56+(i%4)*236,y:75+Math.floor(i/4)*229,w:180,h:172}));
export const LAUNCH_DURATION=.68;
const colors=['#1b9492','#3972ce','#6752b8','#d48638','#32785f','#bc628d','#428bae','#be843d'];
const glyphs=['S','↗','↗','SL','A','R','W','T'];
const ease=t=>{t=THREE.MathUtils.clamp(t,0,1);return 1-Math.pow(1-t,3);};

export function createProjectScreens(monitors,{onSelect=()=>{},onLink=()=>{},onDesktop=()=>{}}={}){
  const entries=Object.entries(PROJECTS),screens=monitors.map(()=>createScreenCanvas());
  const original=monitors.map(m=>m.material),originalGeometry=monitors.map(m=>m.geometry),geometry=monitors.map(()=>new THREE.PlaneGeometry(1.225,.785));
  const materials=screens.map(s=>new THREE.MeshBasicMaterial({map:s.texture,toneMapped:false}));
  let selected=0,awake=false,phase='desktop',elapsed=0,buttons=[[],[]],hover=-1,lastMinute='';
  const images=entries.map(([,p])=>{const img=document.createElement('img');img.onload=()=>draw();img.src=p.img;return img;});
  const wallpaper=document.createElement('img'),idle=createScreenCanvas();
  function imageFit(s,img,x,y,w,h,cover=false){
    if(!img.complete||!img.naturalWidth)return;
    const scale=(cover?Math.max:Math.min)(w/img.naturalWidth,h/img.naturalHeight),iw=img.naturalWidth*scale,ih=img.naturalHeight*scale;
    s.ctx.save();s.ctx.beginPath();s.ctx.rect(x,y,w,h);s.ctx.clip();s.ctx.drawImage(img,x+(w-iw)/2,y+(h-ih)/2,iw,ih);s.ctx.restore();
  }
  function background(s){s.rect(0,0,1000,640,'#17463f');imageFit(s,wallpaper,0,0,1000,640,true);}
  wallpaper.onload=()=>{
    background(idle);idle.finish();
    // Resting monitors also use the wallpaper, with ordinary, unwarped UVs.
    monitors.forEach((m,i)=>{
      original[i].map=idle.texture;original[i].needsUpdate=true;
      const uv=originalGeometry[i].getAttribute('uv'),pos=originalGeometry[i].getAttribute('position');
      for(let n=0;n<uv.count;n++)uv.setXY(n,pos.getX(n)/1.225+.5,pos.getY(n)/.785+.5);
      uv.needsUpdate=true;
    });draw();
  };
  wallpaper.src='./assets/desktop-wallpaper.png';
  function icon(s,index,x,y,size=76){
    s.ctx.save();s.ctx.shadowColor='#041c4266';s.ctx.shadowBlur=14;s.ctx.shadowOffsetY=5;
    s.rect(x,y,size,size,colors[index],size*.22);s.ctx.shadowBlur=0;s.ctx.shadowOffsetY=0;
    s.rect(x+size*.12,y+size*.1,size*.76,size*.31,'#ffffff18',size*.12);
    s.ctx.textAlign='center';s.text(glyphs[index],x+size*.5,y+size*.72,size*.57,'#fff','sans-serif');s.ctx.restore();
  }
  function taskbar(s){
    s.rect(0,586,1000,54,'#dbe9f3ed');
    for(const x of [421,440])for(const y of [597,616])s.rect(x,y,14,14,'#227bcc',1);
    s.rect(478,597,40,34,'#f7bd50',5);s.rect(481,591,19,10,'#e2a539',3);
    if(phase!=='desktop'){icon(s,selected,547,595,34);s.rect(553,633,23,3,'#226eba',2);}
    const time=new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});
    s.ctx.textAlign='right';s.text(time,973,622,24,'#2a3a46','sans-serif');s.ctx.textAlign='left';
  }
  function desktop(s,interactive){
    background(s);s.rect(0,0,1000,586,'#061a2238');
    DESKTOP_ICONS.forEach((item,i)=>{
      if(interactive&&hover===i){s.rect(item.x,item.y,item.w,item.h,'#d5edff35',8);s.ctx.strokeStyle='#dcf1ff66';s.ctx.lineWidth=1;s.ctx.strokeRect(item.x,item.y,item.w,item.h);}
      const x=item.x+(item.w-80)/2,y=item.y+12;icon(s,i,x,y,80);
      s.rect(x-5,y+64,25,25,'#f1f6fb',3);s.text('↗',x-3,y+86,28,'#2c5b92','sans-serif');
      s.ctx.save();s.ctx.textAlign='center';s.ctx.shadowColor='#001116';s.ctx.shadowBlur=5;s.ctx.shadowOffsetY=2;
      const title=entries[i][1].title,lines=title==='SignLang Interface'?['SignLang','Interface']:[title];
      lines.forEach((line,j)=>s.text(line,item.x+item.w/2,item.y+125+j*33,31,'#fff','sans-serif'));s.ctx.restore();
      if(interactive)buttons[1].push({...item,action:{select:i}});
    });taskbar(s);
  }
  function appWindow(s,progress){
    const [id,p]=entries[selected],from=DESKTOP_ICONS[selected],t=ease(progress);
    const x=THREE.MathUtils.lerp(from.x+50,26,t),y=THREE.MathUtils.lerp(from.y+15,28,t),w=THREE.MathUtils.lerp(80,948,t),h=THREE.MathUtils.lerp(80,536,t);
    s.ctx.save();s.ctx.translate(x,y);s.ctx.scale(w/948,h/536);s.ctx.globalAlpha=t;
    s.ctx.shadowColor='#07172699';s.ctx.shadowBlur=24;s.ctx.shadowOffsetY=12;s.rect(0,0,948,536,'#f6f8fb',14);s.ctx.shadowBlur=0;s.ctx.shadowOffsetY=0;
    s.rect(0,0,948,54,'#e3ebf2',14);s.rect(0,32,948,22,'#e3ebf2');icon(s,selected,17,12,29);
    s.text(id+'.exe',60,36,26,'#394e60','sans-serif');s.text('—',789,34,27,'#455763');s.text('□',844,34,27,'#455763');s.text('×',899,37,35,'#455763');
    s.text(p.title,34,117,p.title.length>16?43:51,'#18334b','sans-serif');
    s.wrap(PROJECT_SUMMARIES[id],34,181,418,33,45,'#3a5266');
    s.rect(490,86,425,329,'#e7edf3',9);imageFit(s,images[selected],501,97,403,307);
    const link=p.links.find(l=>l.href.includes('github.com'))||p.links[0];
    s.rect(34,415,418,68,'#236bb5',9);s.text(link.href.includes('github.com')?'View on GitHub ↗':'Visit Synari ↗',55,458,32,'#fff','sans-serif');
    s.text('Built by Dheer',491,459,27,'#6c7d8a','sans-serif');s.ctx.restore();
    if(phase==='open')buttons[1].push({x:808,y:28,w:66,h:54,action:{close:true}},{x:898,y:28,w:76,h:54,action:{close:true}},{x:60,y:443,w:418,h:68,action:{link:link.href}});
  }
  function draw(){
    buttons=[[],[]];const left=screens[0],right=screens[1];background(left);
    if(phase==='desktop')desktop(right,true);
    else{
      desktop(right,false);
      if(phase==='launching'&&elapsed<.16){right.rect(260,489,480,54,'#112c3eec',9);right.text('Starting '+entries[selected][0]+'.exe',283,524,25,'#eaf4ff','sans-serif');}
      appWindow(right,phase==='open'?1:(elapsed-.12)/(LAUNCH_DURATION-.12));
    }
    screens.forEach(s=>s.finish());
  }
  function select(index){selected=THREE.MathUtils.clamp(index,0,entries.length-1);phase='launching';elapsed=0;hover=-1;draw();onSelect(selected);}
  function desktopView(){phase='desktop';elapsed=0;hover=-1;draw();onDesktop();}
  return {
    wake(){awake=true;phase='desktop';elapsed=0;monitors.forEach((m,i)=>{m.material=materials[i];m.geometry=geometry[i];});draw();},
    sleep(){awake=false;phase='desktop';elapsed=0;monitors.forEach((m,i)=>{m.material=original[i];m.geometry=originalGeometry[i];});},
    update(dt=0,reduced=false){if(!awake)return;if(phase==='launching'){elapsed=reduced?LAUNCH_DURATION:Math.min(LAUNCH_DURATION,elapsed+dt);if(elapsed===LAUNCH_DURATION)phase='open';draw();}else{const minute=Math.floor(Date.now()/60000);if(minute!==lastMinute){lastMinute=minute;draw();}}},
    select,desktop:desktopView,
    pointer(hit,click=false){const b=hit&&hitButton(buttons[hit.index],hit.u*1000,hit.v*640),next=b?.action.select??-1;if(next!==hover){hover=next;draw();}if(click&&b){if(b.action.select!==undefined)select(b.action.select);else if(b.action.close)desktopView();else if(b.action.link)onLink(b.action.link);}return Boolean(b);},
    get phase(){return phase;},get selected(){return selected;},get project(){return entries[selected][1];},get awake(){return awake;},
  };
}
